### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [TSedlar/LNReader#10]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

It's somehow related to #8 . As long as all your source code is FLOSS, and as long as there is no proprietary dependencies or plugins, I think it should be ok for F-Droid.

**Comment by TSedlar** [comment]
It's perfectly fine if you want to work on that! @Poussinou 

I did start to but some issues were brought up [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/4970).

**Comment by cajeiri** [comment]
I also support F-droid  inclusion.

I'm not a programmer, but I'm guessing based on what's written on gitlab that the issues are a bit harder to fix, or?

**Comment by Poussinou** [comment]
@TSedlar I missed the fdroiddata MR, sorry. Could you please resolve the different Issues raised by Izzy on your MR on gitlab? Looks pretty easy to do so.

**Comment by TSedlar** [comment]
I've got too much going on currently, but feel free.

**Comment by IzzySoft** [comment]
@TSedlar if you just could fix [your currently open MR](https://gitlab.com/fdroid/fdroiddata/merge_requests/4970) (like described there: add the two empty lines, set AutoUpdateMode to None for now), we could proceed with that. All else can be fixed up later (see my comment there). Thanks!

**Comment by cajeiri** [comment]
@TSedlar Update available on F-Droid merging. There seems to be an issue with a missing Flutter SDK (explained in the above MR link) and the Fastlane structure needs to be added to this repo, not via gitlab, as far as I understood.

**Comment by TSedlar** [comment]
I'm entirely willing to accept any pull requests as I've said previously.
I've too much on my plate with school/work/family to get all of this build process working.

It can perfectly be downloaded from the repository on GitHub, XDA Labs, or being built from source in the meanwhile.
