### ISSUE TITLE
Issue with novelplanet 

### ISSUE THREAD

**Issue by ArcaneBeing** [TSedlar/LNReader#12]
There is issue with novelplanet site and wuxiaworld not showing chapters and novel I am reading is only available on them. So plz add www.readlightnovel.org
Or fix wuxiaworld issue.
Thank you.

**Comment by roshavagarga** [comment]
This isn't being maintained, I'd advise switching to something like https://github.com/Shosetsu

**Comment by roshavagarga** [comment]
@ArcaneBeing Wrong link - https://github.com/shosetsuorg/android-app
